### ISSUE TITLE
Show price as column in resources list table

### ISSUE THREAD

**Issue by Derkades** [samerton/Nameless-Resources#28]
Avoids people needing to put [FREE] or a price in the resource title

![image](https://user-images.githubusercontent.com/15892014/105377270-e8cb5480-5c0a-11eb-8d9e-988d832cd6af.png)

**Comment by partydragen** [comment]
Added in https://github.com/samerton/Nameless-Resources/pull/31
![Skjermbilde](https://user-images.githubusercontent.com/9625439/109361101-a8ee3180-7888-11eb-91b9-470ba9d2ac0f.PNG)

**Comment by samerton** [comment]
https://github.com/samerton/Nameless-Resources/releases/tag/v1.4.0
