### ISSUE TITLE
[Question] How to expose premium resources to guests?

### ISSUE THREAD

**Issue by PikaMug** [samerton/Nameless-Resources#38]
Currently, paid resources are hidden from unregistered site visitors on my site. I see this is not the case on the NamelessMC site. Where can I toggle this setting?

**Comment by samerton** [comment]
Paid resources show in the list for guests as normal, see https://namelessmc.com/resources/category/2-namelessmc-templates/ as an example

There is no extra configuration required for this - if a guest can view a category, they can view all resources (including paid) inside.

**Comment by PikaMug** [comment]
Thanks for the reply. Like you mentioned, the issue was category permissions. Sorry for the inconvenience!
