### ISSUE TITLE
Error with Paypal

### ISSUE THREAD

**Issue by Thomas-botc** [samerton/Nameless-Resources#41]
Hello I am currently using NamelessMC v2 and I have the resource module but when I buy the resource its done, can anyone help me?

Error is :
Fatal error: Uncaught Error: Class 'PayPal\Api\Payer' not found in /var/www/pterodactyl-template-france.com/modules/Resources/pages/resources/purchase.php:165 Stack trace: #0 /var/www/pterodactyl-template-france.com/index.php(106): require() #1 {main} thrown in /var/www/pterodactyl-template-france.com/modules/Resources/pages/resources/purchase.php on line 165
![unknown](https://user-images.githubusercontent.com/78816254/123455862-7b20bb80-d5e2-11eb-8bac-2f3086af8d65.png)

**Comment by samerton** [comment]
It looks like you're missing some files, can you please re-upload the `modules/Resources/PayPal-PHP-SDK` folder from the Resources module onto your web host

**Comment by Thomas-botc** [comment]
Yes it's good its bug anymore but now its done when I try to buy it
![unknown (1)](https://user-images.githubusercontent.com/78816254/123456404-174ac280-d5e3-11eb-9009-33853b68cf56.png)

**Comment by samerton** [comment]
Can you check the file `cache/logs/other-log.log` for errors

**Comment by Thomas-botc** [comment]
Yes as soon as I put my client ID and secret client his remake, here are the files:
[File.zip](https://github.com/samerton/Nameless-Resources/files/6717608/File.zip)

**Comment by Thomas-botc** [comment]
So?

**Comment by samerton** [comment]
Have you checked the file `cache/logs/other-log.log` for errors?

**Comment by Thomas-botc** [comment]
There is no errors :/

**Comment by samerton** [comment]
Which files do you see in the `cache/logs` folder?

**Comment by Thomas-botc** [comment]
fatal-log.log
other-log.log
PayPal.log

**Comment by samerton** [comment]
Is there anything inside the files `other-log.log` or is it empty?

**Comment by Thomas-botc** [comment]
No there are things inside

**Comment by Thomas-botc** [comment]
I don't think I have the latest version of your module. Can you send me the latest version of Nameless-Resources?

**Comment by samerton** [comment]
The latest version is 1.4.0, available here: https://github.com/samerton/Nameless-Resources/releases/tag/v1.4.0

**Comment by Thomas-botc** [comment]
ok but if i change the version i will lose the resources i currently have? if so how can i save them?

**Comment by samerton** [comment]
You won't lose any resources when you update the module.

If you're uncertain, feel free to back up your files and the database first.

**Comment by Thomas-botc** [comment]
okay thanks!

**Comment by Thomas-botc** [comment]
Hello again, I allow myself to reopen the ticket but I just put the new version and its done ??
![Screenshot_1](https://user-images.githubusercontent.com/78816254/123462434-9bed0f00-d5ea-11eb-8855-362adff31776.png)

**Comment by samerton** [comment]
Feel free to re-open the ticket any time

You might also have to update the template you are using - if you switch to the Default Revamp template, does it look normal?

**Comment by Thomas-botc** [comment]
Yes indeed it comes from the template I will update it sorry ^^
