### ISSUE TITLE
Question and problem

### ISSUE THREAD

**Issue by Thomas-botc** [samerton/Nameless-Resources#42]
Hello, is it normal that `modules/Resources/paypal.php` will delete everything that has in it after having put the Paypal Client ID and the Paypal Client Secret?

**Comment by samerton** [comment]
I don't know why that would happen I'm afraid.

You can create the file manually by copying `modules/Resources/paypal_default.php` and renaming the copy to `modules/Resources/paypal.php` - then replace `{client_id}` and `{client_secret}` near the top of the file accordingly.

Note, the file `modules/Resources/paypal_default.php` needs to stay, so make sure you copy + rename instead of simply renaming the original.

**Comment by Thomas-botc** [comment]
Okay, I followed what I said but I always have a mistake when I order a resource
![Screenshot_33333](https://user-images.githubusercontent.com/78816254/123471010-79142800-d5f5-11eb-9c5a-12aa928b212a.png)
![Screenshot_4444444](https://user-images.githubusercontent.com/78816254/123471014-79acbe80-d5f5-11eb-87c0-a1e40a7f0f83.png)
![unknown (1)](https://user-images.githubusercontent.com/78816254/123471017-79acbe80-d5f5-11eb-8bd3-e429729dc037.png)

**Comment by Thomas-botc** [comment]
So?

**Comment by samerton** [comment]
Can you remove `{` and `}` from around your client ID and secret?

**Comment by Thomas-botc** [comment]
No there is always the error
![Screenshot_3](https://user-images.githubusercontent.com/78816254/123489821-1cc00100-d613-11eb-8610-f932bdd99ecd.png)

**Comment by samerton** [comment]
Can you please edit the file `modules/Resources/pages/resources/purchase.php` in a text editor, delete all code inside and replace with this new code: https://gist.githubusercontent.com/samerton/f92247e925e0a52a71d1d1cdfc4c6f6c/raw/37f3eb495a6d8261698ab2f9550b15219c1e90f9/purchase.php

Then, when you try purchasing a resource, the full error message should appear on screen.

**Comment by Thomas-botc** [comment]
The Error is : 
`{"error":"invalid_client","error_description":"Client Authentication failed"}1`

**Comment by Thomas-botc** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/78816254/123522550-28b4cd00-d6be-11eb-8a78-b8f481d2660e.png)

**Comment by Thomas-botc** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/78816254/123522564-39fdd980-d6be-11eb-93b0-3f448ccd2958.png)

**Comment by samerton** [comment]
The client ID and secret are incorrect.

Can you ensure you are using a real client ID and secret, and not the sandbox credentials

**Comment by Thomas-botc** [comment]
I put his :
![Screenshot_3](https://user-images.githubusercontent.com/78816254/123522616-982abc80-d6be-11eb-8705-d831f9e856f9.png)

**Comment by samerton** [comment]
As you can see, they are the sandbox API credentials, which will not work on the live PayPal API environment.

Try to find the area where you can generate credentials for the live API, not the sandbox API.

**Comment by Thomas-botc** [comment]
That's it ?
![image](https://user-images.githubusercontent.com/78816254/123522662-f48ddc00-d6be-11eb-9954-4f2ed9087450.png)

**Comment by Thomas-botc** [comment]
![image](https://user-images.githubusercontent.com/78816254/123522674-0a030600-d6bf-11eb-9e36-c0591cb9f468.png)

**Comment by samerton** [comment]
Yes, that looks correct

**Comment by Thomas-botc** [comment]
Ok thanks i will try

**Comment by Thomas-botc** [comment]
Okay ! It works, thank you!

**Comment by samerton** [comment]
No problem - you can revert the contents of the file `modules/Resources/pages/resources/purchase.php` back to its [original code](https://raw.githubusercontent.com/samerton/Nameless-Resources/master/upload/modules/Resources/pages/resources/purchase.php) now

**Comment by Thomas-botc** [comment]
Yes ^^
