### ISSUE TITLE
Moderation tooltip not on top

### ISSUE THREAD

**Issue by PikaMug** [samerton/Nameless-Resources#44]
Using with pr-10, when selecting the Moderation button on a resource **without** reviews, a few of the tooltip options like "Manage Licenses" are hidden beneath the footer. Default template, latest Firefox or Chrome.

![tooltip](https://user-images.githubusercontent.com/2267126/123864645-fe9b1f00-d8f8-11eb-9300-1f5e4c6954a5.png)

**Comment by samerton** [comment]
Thanks for the report, 38d3c176deeb6104420dfea6d9f0ca78ab3c064a will ensure it shows on top

Note this will require the next Nameless release (pre-11 or the full v2, depending on how it's released), specifically [this commit](https://github.com/NamelessMC/Nameless/commit/a6d0f1cca928c0c1eda1cea70ce6968ff794936f)
