### ISSUE TITLE
Problem v13

### ISSUE THREAD

**Issue by BrayaanPS** [samerton/Nameless-Resources#62]
Hello, when using the module in version v13, I get these errors
1. Resource icons are not visible 
![chrome_JaGs5UZ3Qq](https://user-images.githubusercontent.com/30274810/172266819-e89490a3-3244-4bc7-8e8b-240afe4d61eb.png)

2. When I try to upload another icon I get the following error
![chrome_hMXEfMPo2F](https://user-images.githubusercontent.com/30274810/172266792-2c9f8329-0338-4457-b2d6-28a5d2aacfbd.png)

**Comment by PadowYT2** [comment]
Already known, Sam is going to rewrite the module

**Comment by PadowYT2** [comment]
I guess close?
