### ISSUE TITLE
Bug when leaving a review

### ISSUE THREAD

**Issue by 1day2die** [samerton/Nameless-Resources#67]
![Screenshot_20220624_212101_org mozilla firefox](https://user-images.githubusercontent.com/8725848/175651701-8a758807-015a-41cd-bc96-44bf96a933d6.jpg)

**Comment by PikaMug** [comment]
Safe to assume f5456b74c390b71b97c4a895f625434b5bb72273 resolved this?

**Comment by samerton** [comment]
Should be resolved in version 1.7.0
