### ISSUE TITLE
Suggestion: paid Ressource creation for certain ranks only

### ISSUE THREAD

**Issue by 1day2die** [samerton/Nameless-Resources#68]
Have only certain ranks be able to create paid resources. That would be cool

**Comment by PadowYT2** [comment]
It is already a thing

**Comment by 1day2die** [comment]
> It is already a thing

Uuuh are you sure? I couldn't find the option and dragen himself said it would be nice to have on discord.

**Comment by PadowYT2** [comment]
![https://cdn.padow.ru/kqoo](https://cdn.padow.ru/kqoo)

**Comment by 1day2die** [comment]
Apparently I'm fucking stupid. That's great news tho!
