### ISSUE TITLE
Price not appearing on resource pages

### ISSUE THREAD

**Issue by PikaMug** [samerton/Nameless-Resources#69]
Nameless pr13 with Resources commit https://github.com/samerton/Nameless-Resources/commit/af8d5fd2bebc9c202336f8b3b645ce2a597a53ee

![price](https://user-images.githubusercontent.com/2267126/175788124-2b7dd36e-e68b-4a5e-8b44-e6577387aa0e.png)

Occurs on all paid resources. Price shows just fine in categories, though.

**Comment by samerton** [comment]
Appears to work for me using the latest release (1.7.1)

**Comment by PikaMug** [comment]
Mistake on my end.
