### ISSUE TITLE
Template issues

### ISSUE THREAD

**Issue by PadowYT2** [samerton/Nameless-Resources#71]
https://dev.namelessmc.xyz/resources/author/1-padowyt2/
![https://cdn.padow.ru/wNmm](https://cdn.padow.ru/wNmm)
![https://cdn.padow.ru/XmZp](https://cdn.padow.ru/XmZp)
And there's https://github.com/samerton/Nameless-Resources/blob/8d9d7c25af42eb6e89c87e153c0069147c94df69/upload/custom/templates/DefaultRevamp/resources/author.tpl#L113-L185 why? same in many files

**Comment by samerton** [comment]
Looks like a merge issue following the merging of PR #70

**Comment by samerton** [comment]
b34d7893bf7674a5a6d5b20de8f5aec06514778a
