### ISSUE TITLE
[CRITICAL?] Single quote corrupts title

### ISSUE THREAD

**Issue by PikaMug** [samerton/Nameless-Resources#82]
Previously, with Nameless 2.0.3, single quotes (`'`) appeared normally in resource titles (i.e. Bob's Mod).

With 2.1.0, all single quotes are converted to `&#039;` on submission. On edit and re-submission, this string will turn into `&amp;#039;` and will continue to "grow" an `amp;` each subsequent entry. While this seems relatively harmless, I'm concerned that other characters may have potential for abuse.

**Comment by samerton** [comment]
Thanks - fortunately just a display issue but I will look at a fix now
