### ISSUE TITLE
Dark-on-dark text in dark mode

### ISSUE THREAD

**Issue by Derkades** [samerton/Nameless-Resources#83]
![image](https://github.com/samerton/Nameless-Resources/assets/15892014/2dc959cd-a3e8-4c24-a8b7-7ec0c22c36c8)

**Comment by samerton** [comment]
To add the cherry on top, we even have white on white! 😄 
<img width="876" alt="Screenshot 2023-05-23 at 18 42 21" src="https://github.com/samerton/Nameless-Resources/assets/1812544/e2af31a8-9119-49f0-bd73-0bc3e5318589">

**Comment by Derkades** [comment]
Beautiful

**Comment by samerton** [comment]
Forgot to close this yesterday after 8da3767224a7eae0a750f28641fb959970e3e64d
