### ISSUE TITLE
Error downloading resource

### ISSUE THREAD

**Issue by ShaneBeee** [samerton/Nameless-Resources#9]
Hello

So Im pretty sure I set everything up correctly, when I attempt to download a resource of mine (I uploaded a zip file) (from another user) I get an error message:
```
Sorry!
Sorry, but something went wrong while loading the page. Please contact an administrator.
```

If I download from my admin account I get the following error message
```
Sorry!
Sorry, but something went wrong while loading the page. Error details:


Uncaught Error: Call to undefined function finfo_open() in /home/shanalth/public_html/forums/modules/Resources/pages/resources/resource.php:736
Stack trace:
#0 /home/shanalth/public_html/forums/index.php(103): require()
#1 {main}
  thrown

in file /home/shanalth/public_html/forums/modules/Resources/pages/resources/resource.php
on line 736
```

**Comment by samerton** [comment]
Hi,

Looks like your web host is missing the `fileinfo` PHP extension. You can try asking them if it's possible to enable it on your site.

**Comment by ShaneBeee** [comment]
Ahh, good to know. Thanks for the info, Ill get in touch with them.

**Comment by samerton** [comment]
I'll mark this as closed, if you're still experiencing issues please feel free to re-open

**Comment by ShaneBeee** [comment]
> I'll mark this as closed, if you're still experiencing issues please feel free to re-open

Hi, sorry I didn't respond sooner. I got busy, but I just contacted my web host, they enabled that extension and it works perfect now.

Thank you again for your assistance.
